name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - main
    workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Bash Test Step
        shell: bash
        run: |
          echo ":)"
